# Generated by Django 5.2 on 2025-12-03 08:37
from datetime import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='event',
        name='time',
    ),
    migrations.AddField(
        model_name='event',
        name='time',
        field=models.TimeField(default=time(0,0)),
        preserve_default=False,
    ),
    ]
